apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bxf4tqw7v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bxf4tqw7v-python 
  name: bxf4tqw7v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bxf4tqw7v-python 
